---
name: Global Cheese Positioning System

on:
  push:
  pull_request:
  schedule:
    - cron: "15 * * * *"

env:
  NAMECHECK_LIST: ${{ secrets.NAMECHECK_LIST }}

jobs:
  runchecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make Temporary Results Dir
        run: mkdir -p temp
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      ### START CHECKS
      - name: Lookup DNS Records
        run: bin/namecheck.py ${NAMECHECK_LIST} > temp/namecheck.json
      ### END CHECKS

      - name: Store Current Results
        uses: actions/upload-artifact@v2
        with:
          name: cheeserun-results-${{github.run_id}}
          path: temp/

  compare:
    needs: runchecks
    runs-on: ubuntu-latest
    env:
      CHANGED: 0
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Restore Latest Results
        uses: actions/download-artifact@v2
        with:
          name: cheeserun-results-${{github.run_id}}
          path: temp/
      - name: Overwrite Saved Results
        run: |
          rm -rf results/*
          cp -r temp/* results/
          git add -A results
      - name: Compare Results
        run: git diff --exit-code --staged results/ >> temp/changeset.diff || echo "CHANGED=1" >> $GITHUB_ENV
      - name: Commit and Push Changes
        if: env.CHANGED == 1
        uses: actions-x/commit@v2
      - name: Output Change Report
        id: changeset
        if: env.CHANGED == 1
        run: |
          cat temp/changeset.diff
          echo "CHANGESET=$(cat temp/changeset.diff | sed 's/\"/\\\"/g' | awk -v ORS='\\\\n' '1')" >> $GITHUB_ENV
      - name: Slack Changes
        # Requires SLACK_WEBHOOK_URL and SLACK_CHANNEL secrets to be
        # set.
        if: env.CHANGED == 1 && github.ref == 'refs/heads/main'
        uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          username: "CheeseWatch"
          channel: ${{ secrets.SLACK_CHANNEL }}
          color: "danger"
          text: "The cheese has moved..."
          fields: |
            [
              {"title": "Run", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"},
              {"title": "Change", "value": "${{ env.CHANGESET }}"}
            ]
