---
name: Change Monitor

on:
  push:
  pull_request:
  schedule:
    - cron: "15 * * * *"

env:
  NAMELIST: "www.login.gov secure.login.gov a.pivcac.prod.login.gov"

jobs:
  runchecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make Temporary Results Dir
        run: mkdir -p results
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      ### START CHECKS
      - name: Lookup DNS Records
        run: bin/namecheck.py ${NAMELIST} > results/namecheck.json
      ### END CHECKS

      - name: Store Current Results
        uses: actions/upload-artifact@v2
        with:
          name: cheeserun-results-${{github.run_id}}
          path: results/

  compare:
    needs: runchecks
    runs-on: ubuntu-latest
    steps:
      - uses: rlespinasse/github-slug-action@v3.x
      - name: Set Consistent REFSLUG
        run: echo "REFSLUG=${GITHUB_REF_SLUG:-unknown}" >> $GITHUB_ENV
      - name: Prepare
        run: |
          mkdir results
          mkdir saved
      - name: Restore Saved Results
        continue-on-error: true
        uses: actions/download-artifact@v2
        with:
          name: cheeserun-saved-${{env.REFSLUG}}
          path: saved/
      - name: Restore Current Results
        uses: actions/download-artifact@v2
        with:
          name: cheeserun-results-${{github.run_id}}
          path: results/
      - name: Compare Results
        run: |
          for f in $(ls -1 results/); do
            diff -uN saved/${f} results/${f} >> results/changeset.diff
          done
      - name: Store Current Results as Saved
        uses: actions/upload-artifact@v2
        with:
          name: cheeserun-saved-${{env.REFSLUG}}
          path: saved/
      - name: Report Changes
        run: |
          if [ -s "results/changeset.diff" ]; then
            echo "::group::Moved Cheese Report"
            cat results/changeset.diff
            echo "::endgroup::"
            exit 1
          fi
