---
name: Change Monitor

on:
  push:
  pull_request:
  schedule:
    - cron: "15 * * * *"

env:
  NAMECHECK_LIST: ${{ secrets.NAMECHECK_LIST }}

jobs:
  runchecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make Temporary Results Dir
        run: mkdir -p results
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      ### START CHECKS
      - name: Lookup DNS Records
        run: bin/namecheck.py ${NAMECHECK_LIST} > results/namecheck.json
      ### END CHECKS

      - name: Store Current Results
        uses: actions/upload-artifact@v2
        with:
          name: cheeserun-results-${{github.run_id}}
          path: results/

  compare:
    needs: runchecks
    runs-on: ubuntu-latest
    env:
      CHANGED: 0
    steps:
      - uses: rlespinasse/github-slug-action@v3.x
      - name: Set Consistent REFSLUG
        run: echo "REFSLUG=${GITHUB_REF_SLUG:-unknown}" >> $GITHUB_ENV
      - name: Prepare
        run: |
          mkdir results
          mkdir saved
      - name: Restore Saved Results
        continue-on-error: true
        uses: actions/download-artifact@v2
        with:
          name: cheeserun-saved-${{env.REFSLUG}}
          path: saved/
      - name: Restore Current Results
        uses: actions/download-artifact@v2
        with:
          name: cheeserun-results-${{github.run_id}}
          path: results/
      - name: Compare Results
        run: git diff --no-index saved/ results/ >> changeset.diff || echo "CHANGED=1" >> $GITHUB_ENV
      - name: Store Current Results as Saved
        uses: actions/upload-artifact@v2
        with:
          name: cheeserun-saved-${{env.REFSLUG}}
          path: results/
      - name: Change Report
        if: env.CHANGED
        run: |
          cat changeset.diff
          echo "::set-output name=changeset::$(cat changeset.diff)"
      - name: Slack Changes
        # Requires SLACK_WEBHOOK_URL and SLACK_CHANNEL secrets to be
        # set.  See
        if: env.CHANGED && github.ref == 'refs/heads/main'
        uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          username: "CheeseWatch"
          channel: ${{ secrets.SLACK_CHANNEL }}
          color: "danger"
          text: "The cheese has moved..."
          fields: |
            [
              {"title": "Run", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"},
              {"title": "Change", "value": "${outputs.changeset"}
            ]
